
name: "构建docker镜像"
on:
  workflow_dispatch:
  schedule:
      - cron: "1 0-23/3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: shuye72/jd-base
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: gitee
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
